install.packages("cancensus")
library(cancensus)
options(cancensus.api_key='CensusMapper_17d2ce97fde1a6b31319965bb10d0fb0')
options(cancensus.cancensus.cache_path ="~")
toronto_ct <- get_census(dataset='CA16', regions=list(CMA="35535"), vectors=c(), labels="detailed", geo_format="sf", level='CT')
toronto_da<- get_census(dataset='CA16', regions=list(CMA="35535"), vectors=c(), labels="detailed", geo_format="sf", level='DA')
library(ggplot2)
ggplot(toronto_ct,aes(geometry=geometry,fill=Population))+geom_sf()
ggsave("population.jpg")
ggplot(toronto_da,aes(geometry=geometry,fill=Population))+geom_sf()
census_data <- get_census(dataset='CA16', regions=list(CMA="35535"), vectors=c("v_CA16_7"), labels="detailed", geo_format='sf', level='CT')
names(census_data)
library(tidyverse)
Toronto2<-rename(census_data, "Toddlers"= `v_CA16_7: 0 to 4 years`)
names(Toronto2)
ggplot(Toronto2, aes(geometry=geometry, fill=Toddlers))+geom_sf()
names(Toronto2)
Toronto3<-mutate(Toronto2, precent=(Toddlers/Population)*100)
ggplot(Toronto3, aes(geometry=geometry, fill=precent)) + geom_sf()+
  scale_fill_gradient(low="firebrick1", high = "firebrick4")+
labs(title = "Precent of Toddlers in Toronto")
